Default_Model_Lang:
  columns:
    lang_id:
      type: integer(4)
      autoincrement: true
      primary: true
    code: 
      type: string(2)
      notnull: true
    index: 
      type: integer(4)
      notnull: true
